version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0

jobs:
  sonarqube-analysis:
    docker:
      - image: cimg/node:16.13
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Set up SonarQube scan environment
          command: |
            echo "Preparing SonarQube analysis with secure credentials"
            # CircleCI will automatically detect if we're running on a PR
      - sonarcloud/scan
  
  security-scan:
    docker:
      - image: cimg/python:3.9-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Install security tools
          command: |
            pip install njsscan
            npm install -g npm-audit-html
      - run:
          name: Run njsscan
          command: |
            njsscan . || echo "Scan completed with findings"
      - run:
          name: Run npm audit
          command: npm audit --audit-level=high || echo "Audit completed with findings"

workflows:
  version: 2
  build-test-scan:
    jobs:
      - sonarqube-analysis:
          context: SonarCloud
      - security-scan 