name: Basic Checks

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  # Allow manual trigger
  workflow_dispatch:

jobs:
  eslint:
    name: ESLint Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm ci || npm install
          
      - name: Run ESLint
        run: npx eslint "**/*.js" --ignore-pattern "node_modules/" --ignore-pattern "lib/" 