name: Security Check (Legacy)

on:
  workflow_dispatch: # Manual trigger only

jobs:
  security-notice:
    name: Security Scan Notice
    runs-on: ubuntu-latest
    steps:
      - name: Security Scanning has moved
        run: |
          echo "Security scanning has been moved to CircleCI"
          echo "This workflow remains for reference but is not actively used"
          exit 0

# Note: Security scanning has been moved to CircleCI
# See .circleci/config.yml for the current implementation
# This includes:
# - CodeQL Analysis
# - NJSScan for Node.js security
# - npm audit
# - SonarQube analysis 